# Generated by Django 5.0.6 on 2024-07-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_alter_storymodel_options_alter_storyview_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storyreactions',
            options={'ordering': ['-id'], 'verbose_name': 'StoryReactions', 'verbose_name_plural': 'StoryReactions'},
        ),
        migrations.AlterModelOptions(
            name='storyreport',
            options={'ordering': ['-id'], 'verbose_name': 'StoryReport', 'verbose_name_plural': 'StoryReports'},
        ),
    ]
