# Generated by Django 5.0.6 on 2024-07-05 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_initial'),
        ('post', '0003_remove_postusermodel_users_postusermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlikemodel',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='comment.commnentmodel'),
        ),
        migrations.AlterField(
            model_name='commnentmodel',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comment.commnentmodel'),
        ),
        migrations.AlterField(
            model_name='commnentmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.postusermodel'),
        ),
    ]
