# Generated by Django 5.0.6 on 2024-07-05 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_commentlikemodel_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commnentmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comment.commnentmodel'),
        ),
    ]
