# Generated by Django 5.0.6 on 2024-07-05 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0003_initial'),
        ('post', '0003_remove_postusermodel_users_postusermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepostmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='post.postusermodel'),
        ),
    ]
